# Generated by Django 5.1.1 on 2024-10-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comrades', '0002_alter_comrades_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comrades',
            name='academic_year',
            field=models.IntegerField(),
        ),
    ]
