# Generated by Django 5.1.1 on 2024-10-11 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departments', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CoursesOffered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseOffered', models.CharField(max_length=255)),
                ('departments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursesOffered', to='departments.departments')),
            ],
        ),
    ]
