# Generated by Django 5.1.1 on 2024-10-11 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursesoffered',
            old_name='courseOffered',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='departments',
            old_name='departments',
            new_name='name',
        ),
    ]
